### ISSUE TITLE
fetch() requests didn't work on workers but working at miniflare local dev

### ISSUE THREAD

**Issue by sinitsa** [edmundhung/remix-worker-template#7]
Hello!

I have tested fetch(), and axios request - in routes files - everything same - at worker, any request did't get any response... at local dev (miniflare) everything ok ....
and by the way, how i can use Cloudflare KV  read/writ in *.server.ts files? I have added everything as usually but in this template seems like something works bit different...
Can you please show me a way...
Thanks in advance

**Comment by edmundhung** [comment]
Hi @sinitsa,

> I have tested fetch(), and axios request - in routes files - everything same - at worker, any request did't get any response... at local dev (miniflare) everything ok ....

I am not sure exactly what's the problem you had here. I haven't try using axios with worker myself. But I do think it might be hard to get it working correctly on the Worker runtime. I would strongly suggest using the native fetch instead.

> and by the way, how i can use Cloudflare KV read/writ in *.server.ts files? I have added everything as usually but in this template seems like something works bit different...

I guess you might be trying to access the KV bindings as global variables. However, this approach is limited to `service worker` (which the official remix worker template is based on), while this template is setup as a `module worker`. You can find out more details about module worker [here](https://developers.cloudflare.com/workers/learning/migrating-to-module-workers/). I understand this is probably quite confusing to new users experimenting Cloudlfare Workers. But in general, you can consider `module worker` as the latest and suggested approach going forward to implement your workers logic. There are also additional benefits with this approach. For example, `module workers` support Durable Objects and works with Pages directly as well.

Back to your question, in order to access the KV binding, you will need to access it through the `env` object similar to the [example here](https://github.com/edmundhung/remix-worker-template/issues/6#issuecomment-1056747173). This approache should allow you to access it on `loader` and `action` which is usually where you usually need the KV.
  
Let me know if you have any more questions. It will be helpful if you can provide more details/code on how you are doing it.

**Comment by sinitsa** [comment]
Thank you so much!
I catch error with fetch (i gave additional invalid mode=cors header param, it's works on local dev but fails on worker)
And finally i make it works with context.env.BINDING KV access in loader, thank you, i understood about module worker difference, planning to dig deeper to Durable Objects, thank you so much for showing me the way ) and big thanks for excellent quality template)
